name: Run Tests
on:
  pull_request:
    branches:
      - master
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: 3.x

      - name: Install Protoc Go plugin
        run: go get -u -v github.com/golang/protobuf/protoc-gen-go

      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Test
        run: make test
